using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

#nullable disable

// <Auto-Generated>
// This is here so CodeMaid doesn't reorganize this document
// </Auto-Generated>

namespace UserLibrary.Domain.Entities
{
    /// <summary>
    /// Persisted company entity
    /// </summary>
    public class Company : BaseEntity
    {
        /// <summary>
        /// No idea
        /// </summary>
        public string Bs { get; set; }

        /// <summary>
        /// Catch phrase
        /// </summary>
        public string CatchPhrase { get; set; }

        /// <summary>
        /// Name
        /// </summary>
        public string Name { get; set; }
    }
}